[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Serve static assets directly (don't redirect to index.html)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling configuration
[forms]
  # Enable form detection
  enabled = true
